### PR TITLE
Utilize hardware acceleration for a cleaner transition on hover

### PR DESCRIPTION
**Pull request by josephfusco**

### CODE REVIEW

**Comment by josephfusco** [comment]
@mx3m Things were getting kind of choppy with using padding to shift the post date and title.  :smile:

**Comment by mx3m** [comment]
Ha! Nice update.

Now I need to have a look at how the animation was done on the side panel... Hopefully, it's using CSS transform too.

**Comment by mx3m** [comment]
Hu, no it's not.

I'll change that too! Thanks ;)

**Comment by josephfusco** [comment]
no problem! yeah i just noticed that its not :)

**Pull request merged**
